import { useParams, useNavigate } from 'react-router-dom';
import { useState } from 'react';

export default function ProjectMemo() {
    const { id } = useParams();
    const navigate = useNavigate();
    const [showEmailModal, setShowEmailModal] = useState(false);
    const [emailAddress, setEmailAddress] = useState('');
    const [emailMessage, setEmailMessage] = useState('');
    const [isSending, setIsSending] = useState(false);
    const [sendStatus, setSendStatus] = useState<'idle' | 'success' | 'error'>('idle');

    // Mock project data - in production, fetch from API
    const project = {
        id: id || '8492',
        name: 'West African Rail Expansion',
        status: 'Feasibility Phase',
        fundingAsk: '$450M',
        readinessScore: 85,
        pillar: 'Infrastructure',
        leadCountry: 'Nigeria',
        leadCompany: 'RailCo Ltd.'
    };

    const handleDownload = () => {
        // Implement PDF download logic
        console.log('Downloading memo as PDF...');
    };

    const handleEmail = () => {
        setShowEmailModal(true);
        setSendStatus('idle');
        setEmailAddress('');
        setEmailMessage('');
    };

    const handleSendEmail = async () => {
        if (!emailAddress || !emailAddress.includes('@')) {
            alert('Please enter a valid email address');
            return;
        }

        setIsSending(true);
        setSendStatus('idle');

        try {
            // Prepare the memo content
            const memoContent = `
INVESTMENT MEMORANDUM

Project: ${project.name}
Project ID: #${project.id}
Generated: ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}

EXECUTIVE SUMMARY
================
The ${project.name} represents a strategic infrastructure initiative aimed at enhancing regional connectivity and economic integration across the ECOWAS region. With a funding requirement of ${project.fundingAsk}, this project aligns with the broader Vision 2050 objectives of integrated infrastructure development.

The project has achieved a readiness score of ${project.readinessScore}/100, indicating strong preparedness for investment consideration. Key stakeholders including the African Development Bank have expressed preliminary support, and technical assessments confirm feasibility with manageable risk factors.

INVESTMENT HIGHLIGHTS
====================
• Economic Impact: Projected IRR of 14% over 25 years with significant job creation potential
• Regional Connectivity: Direct alignment with ECOWAS Vision 2050 Goal 3, reducing transit times by 40%
• Environmental Benefits: Reduction of 150k tons of carbon emissions annually
• Stakeholder Support: Preliminary backing from AfDB and strong member state commitment

RISK ASSESSMENT & MITIGATION
============================
Urban Displacement Risk (Medium): Potential displacement in Lagos suburbs requires comprehensive resettlement action plan with fair compensation mechanisms.

Environmental Compliance (Low): EIA requires updating - addendum in progress, expected completion within 30 days.

FINANCIAL OVERVIEW
==================
Total Investment Required: ${project.fundingAsk} USD
Projected IRR: 14%
Investment Period: 25 Years
Current Phase: ${project.status}

RECOMMENDATION
==============
PROCEED TO INVESTMENT COMMITTEE REVIEW

Based on comprehensive analysis, this project demonstrates strong alignment with ECOWAS strategic objectives, solid financial fundamentals, and manageable risk profile. The high readiness score of ${project.readinessScore}/100 indicates preparedness for advancement to the next stage.

Recommended Action: Advance to Investment Committee for formal approval pending completion of updated EIA documentation.

---
Generated by ECOWAS AI Agent System
            `.trim();

            // Call the supervisor agent to send email
            const response = await fetch('/api/v1/agents/supervisor/send-email', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${localStorage.getItem('token')}`
                },
                body: JSON.stringify({
                    to_email: emailAddress,
                    subject: `Investment Memo: ${project.name}`,
                    body: emailMessage || `Please find attached the investment memorandum for ${project.name}.`,
                    memo_content: memoContent,
                    project_id: project.id,
                    project_name: project.name
                })
            });

            if (!response.ok) {
                throw new Error('Failed to send email');
            }

            const data = await response.json();
            console.log('Email send response:', data);
            setSendStatus('success');

            // Close modal after 3 seconds to allow reading the message
            setTimeout(() => {
                setShowEmailModal(false);
                setEmailAddress('');
                setEmailMessage('');
            }, 3000);
        } catch (error) {
            console.error('Error sending email:', error);
            setSendStatus('error');
        } finally {
            setIsSending(false);
        }
    };

    return (
        <div className="font-display bg-background-light dark:bg-background-dark text-[#0d121b] dark:text-white min-h-screen">
            {/* Top Navbar */}
            <header className="sticky top-0 z-50 w-full bg-white dark:bg-[#1a202c] border-b border-[#e7ebf3] dark:border-[#2d3748]">
                <div className="px-6 lg:px-10 py-3 flex items-center justify-between gap-6">
                    <div className="flex items-center gap-8">
                        <div className="flex items-center gap-3">
                            <div className="size-8 rounded-full bg-[#1152d4]/10 flex items-center justify-center text-[#1152d4]">
                                <span className="material-symbols-outlined">shield_person</span>
                            </div>
                            <h2 className="text-lg font-bold leading-tight tracking-[-0.015em] hidden sm:block">ECOWAS TWG System</h2>
                        </div>
                        <div className="hidden md:flex items-center bg-[#f0f2f5] dark:bg-[#2d3748] rounded-lg h-10 w-64 px-3 gap-2">
                            <span className="material-symbols-outlined text-[#4c669a] dark:text-[#a0aec0]">search</span>
                            <input
                                className="bg-transparent border-none outline-none text-sm w-full placeholder:text-[#4c669a] dark:placeholder:text-[#a0aec0] text-[#0d121b] dark:text-white focus:ring-0 p-0"
                                placeholder="Search projects..."
                                type="text"
                            />
                        </div>
                    </div>
                    <div className="flex items-center gap-6">
                        <nav className="hidden lg:flex items-center gap-6">
                            <a className="text-[#4c669a] dark:text-[#a0aec0] hover:text-[#1152d4] dark:hover:text-white text-sm font-medium transition-colors" href="/dashboard">Dashboard</a>
                            <a className="text-[#1152d4] dark:text-white text-sm font-medium transition-colors border-b-2 border-[#1152d4] pb-0.5" href="/deal-pipeline">Deal Pipeline</a>
                            <a className="text-[#4c669a] dark:text-[#a0aec0] hover:text-[#1152d4] dark:hover:text-white text-sm font-medium transition-colors" href="#">Reports</a>
                            <a className="text-[#4c669a] dark:text-[#a0aec0] hover:text-[#1152d4] dark:hover:text-white text-sm font-medium transition-colors" href="#">Settings</a>
                        </nav>
                        <div className="flex items-center gap-4 border-l border-[#e7ebf3] dark:border-[#2d3748] pl-6">
                            <button className="relative text-[#4c669a] dark:text-[#a0aec0] hover:text-[#1152d4] dark:hover:text-white transition-colors">
                                <span className="material-symbols-outlined">notifications</span>
                            </button>
                            <div className="h-10 w-10 rounded-full bg-cover bg-center border border-[#e7ebf3] dark:border-[#2d3748] bg-gray-300"></div>
                        </div>
                    </div>
                </div>
            </header>

            {/* Main Content */}
            <main className="px-6 lg:px-40 py-8">
                <div className="max-w-[900px] mx-auto">
                    {/* Breadcrumbs */}
                    <div className="flex items-center gap-2 text-sm text-[#4c669a] dark:text-[#a0aec0] mb-6">
                        <button onClick={() => navigate('/dashboard')} className="hover:text-[#1152d4] transition-colors">Home</button>
                        <span className="material-symbols-outlined text-[16px]">chevron_right</span>
                        <button onClick={() => navigate('/deal-pipeline')} className="hover:text-[#1152d4] transition-colors">Deal Pipeline</button>
                        <span className="material-symbols-outlined text-[16px]">chevron_right</span>
                        <button onClick={() => navigate(`/deal-pipeline/${id}`)} className="hover:text-[#1152d4] transition-colors">{project.name}</button>
                        <span className="material-symbols-outlined text-[16px]">chevron_right</span>
                        <span className="text-[#0d121b] dark:text-white font-medium">Investment Memo</span>
                    </div>

                    {/* Header with Actions */}
                    <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8">
                        <div>
                            <div className="flex items-center gap-3 mb-2">
                                <span className="material-symbols-outlined text-[#1152d4] text-3xl">auto_awesome</span>
                                <h1 className="text-3xl font-black text-[#0d121b] dark:text-white">AI-Generated Investment Memo</h1>
                            </div>
                            <p className="text-[#4c669a] dark:text-[#a0aec0]">Generated for: {project.name}</p>
                        </div>
                        <div className="flex gap-3">
                            <button onClick={handleEmail} className="flex items-center gap-2 px-4 py-2 bg-white dark:bg-[#2d3748] border border-[#e7ebf3] dark:border-[#2d3748] rounded-lg text-[#4c669a] dark:text-[#a0aec0] text-sm font-bold hover:bg-[#f6f6f8] dark:hover:bg-[#0d121b] transition-colors">
                                <span className="material-symbols-outlined text-[18px]">email</span>
                                Email
                            </button>
                            <button onClick={handleDownload} className="flex items-center gap-2 px-4 py-2 bg-[#1152d4] text-white rounded-lg text-sm font-bold shadow-md hover:bg-blue-700 transition-colors">
                                <span className="material-symbols-outlined text-[18px]">download</span>
                                Download PDF
                            </button>
                        </div>
                    </div>

                    {/* AI Notice Banner */}
                    <div className="bg-gradient-to-r from-purple-50 to-blue-50 dark:from-purple-950/30 dark:to-blue-950/30 border border-purple-200 dark:border-purple-800/50 rounded-xl p-4 mb-8 flex items-start gap-3">
                        <span className="material-symbols-outlined text-purple-600 dark:text-purple-400 mt-0.5">info</span>
                        <div className="flex-1">
                            <h3 className="text-sm font-bold text-[#0d121b] dark:text-white mb-1">AI-Generated Content</h3>
                            <p className="text-sm text-[#4c669a] dark:text-[#a0aec0]">This memo was automatically generated by our AI agent based on project data and documentation. Please review for accuracy before sharing with stakeholders.</p>
                        </div>
                    </div>

                    {/* Memo Document */}
                    <div className="bg-white dark:bg-[#1a202c] rounded-xl border border-[#e7ebf3] dark:border-[#2d3748] shadow-lg p-12 mb-8">
                        {/* Memo Header */}
                        <div className="border-b-2 border-[#e7ebf3] dark:border-[#2d3748] pb-6 mb-8">
                            <div className="flex justify-between items-start mb-4">
                                <div>
                                    <h2 className="text-2xl font-bold text-[#0d121b] dark:text-white mb-2">INVESTMENT MEMORANDUM</h2>
                                    <p className="text-sm text-[#6b7280]">Project ID: #{project.id}</p>
                                </div>
                                <div className="text-right">
                                    <p className="text-sm text-[#6b7280]">Generated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
                                    <div className="flex items-center gap-1 justify-end text-xs text-purple-600 dark:text-purple-400 mt-1">
                                        <span className="material-symbols-outlined text-[14px]">smart_toy</span>
                                        <span>AI Generated</span>
                                    </div>
                                </div>
                            </div>
                            <h3 className="text-xl font-bold text-[#0d121b] dark:text-white">{project.name}</h3>
                            <p className="text-sm text-[#6b7280] mt-1">{project.pillar} • {project.leadCountry}</p>
                        </div>

                        {/* Executive Summary */}
                        <section className="mb-8">
                            <h4 className="text-lg font-bold text-[#0d121b] dark:text-white mb-4 flex items-center gap-2">
                                <span className="w-1 h-6 bg-[#1152d4] rounded"></span>
                                Executive Summary
                            </h4>
                            <div className="text-[#4c669a] dark:text-[#a0aec0] space-y-3 leading-relaxed">
                                <p>
                                    The {project.name} represents a strategic infrastructure initiative aimed at enhancing regional connectivity and economic integration across the ECOWAS region. With a funding requirement of {project.fundingAsk}, this project aligns with the broader Vision 2050 objectives of integrated infrastructure development.
                                </p>
                                <p>
                                    The project has achieved a readiness score of {project.readinessScore}/100, indicating strong preparedness for investment consideration. Key stakeholders including the African Development Bank have expressed preliminary support, and technical assessments confirm feasibility with manageable risk factors.
                                </p>
                            </div>
                        </section>

                        {/* Investment Highlights */}
                        <section className="mb-8">
                            <h4 className="text-lg font-bold text-[#0d121b] dark:text-white mb-4 flex items-center gap-2">
                                <span className="w-1 h-6 bg-[#1152d4] rounded"></span>
                                Investment Highlights
                            </h4>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div className="bg-[#f6f6f8] dark:bg-[#0d121b] rounded-lg p-4">
                                    <div className="flex items-center gap-2 mb-2">
                                        <span className="material-symbols-outlined text-green-600 dark:text-green-400">trending_up</span>
                                        <h5 className="font-bold text-[#0d121b] dark:text-white">Economic Impact</h5>
                                    </div>
                                    <p className="text-sm text-[#4c669a] dark:text-[#a0aec0]">Projected IRR of 14% over 25 years with significant job creation potential across the region.</p>
                                </div>
                                <div className="bg-[#f6f6f8] dark:bg-[#0d121b] rounded-lg p-4">
                                    <div className="flex items-center gap-2 mb-2">
                                        <span className="material-symbols-outlined text-blue-600 dark:text-blue-400">hub</span>
                                        <h5 className="font-bold text-[#0d121b] dark:text-white">Regional Connectivity</h5>
                                    </div>
                                    <p className="text-sm text-[#4c669a] dark:text-[#a0aec0]">Direct alignment with ECOWAS Vision 2050 Goal 3, reducing transit times by 40%.</p>
                                </div>
                                <div className="bg-[#f6f6f8] dark:bg-[#0d121b] rounded-lg p-4">
                                    <div className="flex items-center gap-2 mb-2">
                                        <span className="material-symbols-outlined text-purple-600 dark:text-purple-400">eco</span>
                                        <h5 className="font-bold text-[#0d121b] dark:text-white">Environmental Benefits</h5>
                                    </div>
                                    <p className="text-sm text-[#4c669a] dark:text-[#a0aec0]">Reduction of 150k tons of carbon emissions annually through modal shift from road to rail.</p>
                                </div>
                                <div className="bg-[#f6f6f8] dark:bg-[#0d121b] rounded-lg p-4">
                                    <div className="flex items-center gap-2 mb-2">
                                        <span className="material-symbols-outlined text-amber-600 dark:text-amber-400">verified</span>
                                        <h5 className="font-bold text-[#0d121b] dark:text-white">Stakeholder Support</h5>
                                    </div>
                                    <p className="text-sm text-[#4c669a] dark:text-[#a0aec0]">Preliminary backing from AfDB and strong commitment from member states.</p>
                                </div>
                            </div>
                        </section>

                        {/* Risk Assessment */}
                        <section className="mb-8">
                            <h4 className="text-lg font-bold text-[#0d121b] dark:text-white mb-4 flex items-center gap-2">
                                <span className="w-1 h-6 bg-[#1152d4] rounded"></span>
                                Risk Assessment & Mitigation
                            </h4>
                            <div className="space-y-4">
                                <div className="flex gap-4 items-start">
                                    <div className="bg-amber-100 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400 rounded-full p-2 mt-1">
                                        <span className="material-symbols-outlined text-[20px]">warning</span>
                                    </div>
                                    <div className="flex-1">
                                        <h5 className="font-bold text-[#0d121b] dark:text-white mb-1">Urban Displacement Risk - Medium</h5>
                                        <p className="text-sm text-[#4c669a] dark:text-[#a0aec0] mb-2">Potential displacement of communities in Lagos suburban areas requires careful management.</p>
                                        <p className="text-sm text-[#0d121b] dark:text-white"><strong>Mitigation:</strong> Comprehensive resettlement action plan with fair compensation mechanisms and community engagement programs.</p>
                                    </div>
                                </div>
                                <div className="flex gap-4 items-start">
                                    <div className="bg-yellow-100 dark:bg-yellow-900/30 text-yellow-600 dark:text-yellow-400 rounded-full p-2 mt-1">
                                        <span className="material-symbols-outlined text-[20px]">schedule</span>
                                    </div>
                                    <div className="flex-1">
                                        <h5 className="font-bold text-[#0d121b] dark:text-white mb-1">Environmental Compliance - Low</h5>
                                        <p className="text-sm text-[#4c669a] dark:text-[#a0aec0] mb-2">Environmental Impact Assessment requires updating as current version is over 6 months old.</p>
                                        <p className="text-sm text-[#0d121b] dark:text-white"><strong>Mitigation:</strong> Updated EIA addendum currently in progress with TWG lead, expected completion within 30 days.</p>
                                    </div>
                                </div>
                            </div>
                        </section>

                        {/* Financial Overview */}
                        <section className="mb-8">
                            <h4 className="text-lg font-bold text-[#0d121b] dark:text-white mb-4 flex items-center gap-2">
                                <span className="w-1 h-6 bg-[#1152d4] rounded"></span>
                                Financial Overview
                            </h4>
                            <div className="bg-[#f6f6f8] dark:bg-[#0d121b] rounded-lg p-6 space-y-4">
                                <div className="flex justify-between items-center pb-3 border-b border-[#e7ebf3] dark:border-[#2d3748]">
                                    <span className="text-[#4c669a] dark:text-[#a0aec0]">Total Investment Required</span>
                                    <span className="text-xl font-bold text-[#0d121b] dark:text-white">{project.fundingAsk} USD</span>
                                </div>
                                <div className="flex justify-between items-center pb-3 border-b border-[#e7ebf3] dark:border-[#2d3748]">
                                    <span className="text-[#4c669a] dark:text-[#a0aec0]">Projected IRR</span>
                                    <span className="text-lg font-bold text-green-600 dark:text-green-400">14%</span>
                                </div>
                                <div className="flex justify-between items-center pb-3 border-b border-[#e7ebf3] dark:border-[#2d3748]">
                                    <span className="text-[#4c669a] dark:text-[#a0aec0]">Investment Period</span>
                                    <span className="font-semibold text-[#0d121b] dark:text-white">25 Years</span>
                                </div>
                                <div className="flex justify-between items-center">
                                    <span className="text-[#4c669a] dark:text-[#a0aec0]">Current Phase</span>
                                    <span className="font-semibold text-[#0d121b] dark:text-white">{project.status}</span>
                                </div>
                            </div>
                        </section>

                        {/* Recommendation */}
                        <section className="mb-8">
                            <h4 className="text-lg font-bold text-[#0d121b] dark:text-white mb-4 flex items-center gap-2">
                                <span className="w-1 h-6 bg-[#1152d4] rounded"></span>
                                Recommendation
                            </h4>
                            <div className="bg-gradient-to-r from-green-50 to-emerald-50 dark:from-green-950/30 dark:to-emerald-950/30 border-l-4 border-green-600 dark:border-green-500 rounded-lg p-6">
                                <div className="flex items-start gap-4">
                                    <div className="bg-green-600 dark:bg-green-500 text-white rounded-full p-2">
                                        <span className="material-symbols-outlined text-[24px]">thumb_up</span>
                                    </div>
                                    <div>
                                        <h5 className="font-bold text-[#0d121b] dark:text-white text-lg mb-2">PROCEED TO INVESTMENT COMMITTEE REVIEW</h5>
                                        <p className="text-[#4c669a] dark:text-[#a0aec0] mb-3">
                                            Based on the comprehensive analysis, this project demonstrates strong alignment with ECOWAS strategic objectives, solid financial fundamentals, and manageable risk profile. The high readiness score of {project.readinessScore}/100 indicates preparedness for advancement to the next stage.
                                        </p>
                                        <p className="text-sm font-semibold text-[#0d121b] dark:text-white">
                                            Recommended Action: Advance to Investment Committee for formal approval pending completion of updated EIA documentation.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </section>

                        {/* Footer */}
                        <div className="border-t-2 border-[#e7ebf3] dark:border-[#2d3748] pt-6 mt-8">
                            <div className="flex items-center justify-between text-sm text-[#6b7280]">
                                <div className="flex items-center gap-2">
                                    <span className="material-symbols-outlined text-[16px]">smart_toy</span>
                                    <span>Generated by ECOWAS AI Agent System</span>
                                </div>
                                <div>
                                    <span>Page 1 of 1</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Action Buttons */}
                    <div className="flex justify-between items-center">
                        <button onClick={() => navigate(`/deal-pipeline/${id}`)} className="flex items-center gap-2 text-[#4c669a] dark:text-[#a0aec0] hover:text-[#1152d4] dark:hover:text-white transition-colors">
                            <span className="material-symbols-outlined">arrow_back</span>
                            Back to Project Details
                        </button>
                        <button className="flex items-center gap-2 px-6 py-3 bg-[#1152d4] text-white rounded-lg text-sm font-bold shadow-lg hover:bg-blue-700 transition-colors">
                            <span className="material-symbols-outlined">edit</span>
                            Edit Memo
                        </button>
                    </div>
                </div>
            </main>

            {/* Email Modal */}
            {showEmailModal && (
                <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
                    <div className="bg-white dark:bg-[#1a202c] rounded-xl border border-[#e7ebf3] dark:border-[#2d3748] shadow-2xl max-w-md w-full">
                        {/* Modal Header */}
                        <div className="flex items-center justify-between p-6 border-b border-[#e7ebf3] dark:border-[#2d3748]">
                            <div className="flex items-center gap-3">
                                <div className="bg-[#1152d4]/10 rounded-full p-2">
                                    <span className="material-symbols-outlined text-[#1152d4]">email</span>
                                </div>
                                <h3 className="text-lg font-bold text-[#0d121b] dark:text-white">Email Investment Memo</h3>
                            </div>
                            <button
                                onClick={() => setShowEmailModal(false)}
                                className="text-[#6b7280] hover:text-[#0d121b] dark:hover:text-white transition-colors"
                            >
                                <span className="material-symbols-outlined">close</span>
                            </button>
                        </div>

                        {/* Modal Body */}
                        <div className="p-6 space-y-4">
                            {sendStatus === 'idle' && (
                                <>
                                    <div>
                                        <label className="block text-sm font-semibold text-[#0d121b] dark:text-white mb-2">
                                            Recipient Email Address *
                                        </label>
                                        <input
                                            type="email"
                                            value={emailAddress}
                                            onChange={(e) => setEmailAddress(e.target.value)}
                                            placeholder="stakeholder@example.com"
                                            className="w-full px-4 py-2.5 bg-[#f6f6f8] dark:bg-[#0d121b] border border-[#e7ebf3] dark:border-[#2d3748] rounded-lg text-[#0d121b] dark:text-white placeholder:text-[#6b7280] focus:outline-none focus:ring-2 focus:ring-[#1152d4] focus:border-transparent"
                                            disabled={isSending}
                                        />
                                    </div>

                                    <div>
                                        <label className="block text-sm font-semibold text-[#0d121b] dark:text-white mb-2">
                                            Custom Message (Optional)
                                        </label>
                                        <textarea
                                            value={emailMessage}
                                            onChange={(e) => setEmailMessage(e.target.value)}
                                            placeholder="Add a personal message to accompany the memo..."
                                            rows={4}
                                            className="w-full px-4 py-2.5 bg-[#f6f6f8] dark:bg-[#0d121b] border border-[#e7ebf3] dark:border-[#2d3748] rounded-lg text-[#0d121b] dark:text-white placeholder:text-[#6b7280] focus:outline-none focus:ring-2 focus:ring-[#1152d4] focus:border-transparent resize-none"
                                            disabled={isSending}
                                        />
                                    </div>

                                    <div className="bg-blue-50 dark:bg-blue-950/30 border border-blue-200 dark:border-blue-800/50 rounded-lg p-3 flex items-start gap-2">
                                        <span className="material-symbols-outlined text-blue-600 dark:text-blue-400 text-sm mt-0.5">info</span>
                                        <p className="text-xs text-[#4c669a] dark:text-[#a0aec0]">
                                            The AI-generated memo will be sent via the ECOWAS AI Agent system using Gmail integration.
                                        </p>
                                    </div>
                                </>
                            )}

                            {sendStatus === 'success' && (
                                <div className="py-8 text-center">
                                    <div className="bg-green-100 dark:bg-green-900/30 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                                        <span className="material-symbols-outlined text-green-600 dark:text-green-400 text-4xl">check_circle</span>
                                    </div>
                                    <h4 className="text-lg font-bold text-[#0d121b] dark:text-white mb-2">Email Sent Successfully!</h4>
                                    <p className="text-sm text-[#4c669a] dark:text-[#a0aec0]">
                                        The investment memo has been sent to {emailAddress}
                                    </p>
                                </div>
                            )}

                            {sendStatus === 'error' && (
                                <div className="py-8 text-center">
                                    <div className="bg-red-100 dark:bg-red-900/30 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                                        <span className="material-symbols-outlined text-red-600 dark:text-red-400 text-4xl">error</span>
                                    </div>
                                    <h4 className="text-lg font-bold text-[#0d121b] dark:text-white mb-2">Failed to Send Email</h4>
                                    <p className="text-sm text-[#4c669a] dark:text-[#a0aec0] mb-4">
                                        There was an error sending the email. Please try again.
                                    </p>
                                    <button
                                        onClick={() => setSendStatus('idle')}
                                        className="text-sm text-[#1152d4] font-semibold hover:underline"
                                    >
                                        Try Again
                                    </button>
                                </div>
                            )}
                        </div>

                        {/* Modal Footer */}
                        {sendStatus === 'idle' && (
                            <div className="flex items-center justify-end gap-3 p-6 border-t border-[#e7ebf3] dark:border-[#2d3748]">
                                <button
                                    onClick={() => setShowEmailModal(false)}
                                    className="px-4 py-2 text-sm font-semibold text-[#4c669a] dark:text-[#a0aec0] hover:text-[#0d121b] dark:hover:text-white transition-colors"
                                    disabled={isSending}
                                >
                                    Cancel
                                </button>
                                <button
                                    onClick={handleSendEmail}
                                    disabled={isSending || !emailAddress}
                                    className="flex items-center gap-2 px-6 py-2.5 bg-[#1152d4] text-white rounded-lg text-sm font-bold shadow-md hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                    {isSending ? (
                                        <>
                                            <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                                            <span>Sending...</span>
                                        </>
                                    ) : (
                                        <>
                                            <span className="material-symbols-outlined text-[18px]">send</span>
                                            <span>Send Email</span>
                                        </>
                                    )}
                                </button>
                            </div>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}
