"""Add missing fields and update enums

Revision ID: 022b7fbab1c5
Revises: 391968dcbfc3
Create Date: 2026-01-07 02:05:42.109918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022b7fbab1c5'
down_revision: Union[str, Sequence[str], None] = '391968dcbfc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if column exists before adding (idempotent migration)
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_name='meetings' AND column_name='transcript'"
    ))
    if not result.fetchone():
        op.add_column('meetings', sa.Column('transcript', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
