"""Add meeting documents

Revision ID: 0e1b80868408
Revises: cb9ba72d0631
Create Date: 2026-01-10 02:49:05.194820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1b80868408'
down_revision: Union[str, Sequence[str], None] = 'cb9ba72d0631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('meeting_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'documents', 'meetings', ['meeting_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'meeting_id')
    # ### end Alembic commands ###
