"""Add document versioning

Revision ID: 1536b62f0df3
Revises: f2ca45523328
Create Date: 2026-01-11 11:48:28.641515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1536b62f0df3'
down_revision: Union[str, Sequence[str], None] = 'f2ca45523328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('documents', sa.Column('parent_document_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'documents', 'documents', ['parent_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'parent_document_id')
    op.drop_column('documents', 'version')
    # ### end Alembic commands ###
