"""add_knowledge_broadcasting_fields

Revision ID: 22e40a99295e
Revises: 1536b62f0df3
Create Date: 2026-01-11 12:14:20.893611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e40a99295e'
down_revision: Union[str, Sequence[str], None] = '1536b62f0df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('scope', sa.JSON(), server_default='["twg_restricted"]', nullable=False))
    op.add_column('documents', sa.Column('category', sa.String(length=50), server_default='twg_specific', nullable=False))
    op.add_column('documents', sa.Column('last_broadcast', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('access_control', sa.String(length=50), server_default='twg_restricted', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'access_control')
    op.drop_column('documents', 'last_broadcast')
    op.drop_column('documents', 'category')
    op.drop_column('documents', 'scope')
    # ### end Alembic commands ###
