"""Add ingested_at to documents

Revision ID: 391968dcbfc3
Revises: c23b4c2df5e4
Create Date: 2026-01-07 01:54:08.899615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '391968dcbfc3'
down_revision: Union[str, Sequence[str], None] = 'c23b4c2df5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ingested_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'ingested_at')
    # ### end Alembic commands ###
