"""create_conflict_table

Revision ID: 398d9eb21944
Revises: d6c4a5045a13
Create Date: 2026-01-08 18:43:32.073480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398d9eb21944'
down_revision: Union[str, Sequence[str], None] = 'd6c4a5045a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conflict_type', sa.Enum('SCHEDULE_CLASH', 'RESOURCE_CONSTRAINT', 'POLICY_MISALIGNMENT', 'DEPENDENCY_BLOCKER', name='conflicttype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='conflictseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('agents_involved', sa.JSON(), nullable=False),
    sa.Column('conflicting_positions', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'NEGOTIATING', 'ESCALATED', 'RESOLVED', 'DISMISSED', name='conflictstatus'), nullable=False),
    sa.Column('resolution_log', sa.JSON(), nullable=True),
    sa.Column('human_action_required', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conflicts')
    # ### end Alembic commands ###
