"""implement_deal_pipeline_lifecycle

Revision ID: 3b4fefa89943
Revises: 691e95d1fe77
Create Date: 2026-01-16 22:13:04.277620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4fefa89943'
down_revision: Union[str, Sequence[str], None] = '691e95d1fe77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'draft'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'pipeline'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'under_review'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'declined'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'needs_revision'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'summit_ready'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'deal_room_featured'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'in_negotiation'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'committed'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'implemented'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'on_hold'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'archived'")
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Use postgresql.ENUM explicitly to avoid reproduction of CREATE TYPE
    from sqlalchemy.dialects import postgresql
    project_status_enum = postgresql.ENUM('DRAFT', 'PIPELINE', 'UNDER_REVIEW', 'DECLINED', 'NEEDS_REVISION', 
        'SUMMIT_READY', 'DEAL_ROOM_FEATURED', 'IN_NEGOTIATION', 'COMMITTED', 'IMPLEMENTED', 'ON_HOLD', 
        'ARCHIVED', 'IDENTIFIED', 'VETTING', 'DUE_DILIGENCE', 'FINANCING', 'DEAL_ROOM', 'BANKABLE', 'PRESENTED', 
        name='projectstatus', create_type=False)
        
    op.create_table('project_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', project_status_enum, nullable=True),
    sa.Column('new_status', project_status_enum, nullable=False),
    sa.Column('changed_by_id', sa.Uuid(), nullable=True),
    sa.Column('change_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_automated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_status_history')
    # ### end Alembic commands ###
