"""Add settings tables

Revision ID: 5576b0b90d58
Revises: 6265edeea1bb
Create Date: 2026-01-16 13:36:15.053417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5576b0b90d58'
down_revision: Union[str, Sequence[str], None] = '6265edeea1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enable_google_calendar', sa.Boolean(), nullable=False),
    sa.Column('enable_zoom', sa.Boolean(), nullable=False),
    sa.Column('enable_teams', sa.Boolean(), nullable=False),
    sa.Column('google_credentials_json', sa.Text(), nullable=True),
    sa.Column('zoom_credentials_json', sa.Text(), nullable=True),
    sa.Column('teams_credentials_json', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=50), nullable=False),
    sa.Column('smtp_config', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twg_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('twg_id', sa.Uuid(), nullable=False),
    sa.Column('meeting_cadence', sa.String(length=50), nullable=True),
    sa.Column('custom_templates', sa.JSON(), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['twg_id'], ['twgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twg_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
