"""Add source_type to meeting_dependencies

Revision ID: 6265edeea1bb
Revises: fe5cd4954a45
Create Date: 2026-01-14 18:56:05.324675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6265edeea1bb'
down_revision: Union[str, Sequence[str], None] = 'fe5cd4954a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    bind = op.get_bind()
    inspector = inspect(bind)
    
    existing_enums = [t['name'] for t in inspector.get_enums('public')]
    
    # Create DependencySource Enum if not exists
    if 'dependencysource' not in existing_enums:
        dependency_source_type = postgresql.ENUM('TWG_PACKET', 'AI_INFERRED', 'MANUAL', name='dependencysource', create_type=False)
        dependency_source_type.create(bind, checkfirst=True)
    
    # Reference existing enum (don't create)
    dependency_source = postgresql.ENUM('TWG_PACKET', 'AI_INFERRED', 'MANUAL', name='dependencysource', create_type=False)

    if inspector.has_table('meeting_dependencies'):
        # Table exists (Dev env), add columns
        columns = [c['name'] for c in inspector.get_columns('meeting_dependencies')]
        
        if 'source_type' not in columns:
            op.add_column('meeting_dependencies', sa.Column('source_type', dependency_source, nullable=False, server_default='MANUAL'))
            op.alter_column('meeting_dependencies', 'source_type', server_default=None)
            
        if 'confidence_score' not in columns:
            op.add_column('meeting_dependencies', sa.Column('confidence_score', sa.Float(), nullable=False, server_default='1.0'))
            op.alter_column('meeting_dependencies', 'confidence_score', server_default=None)
            
        if 'created_by_agent' not in columns:
            op.add_column('meeting_dependencies', sa.Column('created_by_agent', sa.String(length=100), nullable=True))

    else:
        # Table does not exist (Prod env), create it
        # Create DependencyType Enum if not exists
        if 'dependencytype' not in existing_enums:
            dependency_type_enum = postgresql.ENUM('FINISH_TO_START', 'START_TO_START', 'FINISH_TO_FINISH', 'START_TO_FINISH', name='dependencytype', create_type=False)
            dependency_type_enum.create(bind, checkfirst=True)
        
        # Reference existing enum (don't create)
        dependency_type = postgresql.ENUM('FINISH_TO_START', 'START_TO_START', 'FINISH_TO_FINISH', 'START_TO_FINISH', name='dependencytype', create_type=False)

        op.create_table('meeting_dependencies',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('source_meeting_id', sa.Uuid(), nullable=False),
            sa.Column('target_meeting_id', sa.Uuid(), nullable=False),
            sa.Column('dependency_type', dependency_type, nullable=False),
            sa.Column('lag_minutes', sa.Integer(), nullable=False, server_default='0'),
            sa.Column('source_type', dependency_source, nullable=False, server_default='MANUAL'),
            sa.Column('confidence_score', sa.Float(), nullable=False, server_default='1.0'),
            sa.Column('created_by_agent', sa.String(length=100), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
            sa.ForeignKeyConstraint(['source_meeting_id'], ['meetings.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['target_meeting_id'], ['meetings.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        
        # Remove defaults
        op.alter_column('meeting_dependencies', 'source_type', server_default=None)
        op.alter_column('meeting_dependencies', 'confidence_score', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # We can't easily know if we created the table or just added columns without storing state.
    # Safe downgrade: check if we added columns, drop them. 
    # Or if users want full rollback, drop table? 
    # Usually better to revert to previous state. Since we don't know previous state perfectly, 
    # we will drop columns if the table persists.
    
    bind = op.get_bind()
    inspector = inspect(bind)
    
    if inspector.has_table('meeting_dependencies'):
         columns = [c['name'] for c in inspector.get_columns('meeting_dependencies')]
         if 'created_by_agent' in columns:
             op.drop_column('meeting_dependencies', 'created_by_agent')
         if 'confidence_score' in columns:
             op.drop_column('meeting_dependencies', 'confidence_score')
         if 'source_type' in columns:
             op.drop_column('meeting_dependencies', 'source_type')
    
    # Drop the Enum type
    dependency_source = sa.Enum('TWG_PACKET', 'AI_INFERRED', 'MANUAL', name='dependencysource')
    dependency_source.drop(op.get_bind())
    # ### end Alembic commands ###
