"""Add source_type to meeting_dependencies

Revision ID: 6265edeea1bb
Revises: fe5cd4954a45
Create Date: 2026-01-14 18:56:05.324675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6265edeea1bb'
down_revision: Union[str, Sequence[str], None] = 'fe5cd4954a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type first
    dependency_source = sa.Enum('TWG_PACKET', 'AI_INFERRED', 'MANUAL', name='dependencysource')
    dependency_source.create(op.get_bind())
    
    op.add_column('meeting_dependencies', sa.Column('source_type', dependency_source, nullable=False, server_default='MANUAL'))
    op.add_column('meeting_dependencies', sa.Column('confidence_score', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('meeting_dependencies', sa.Column('created_by_agent', sa.String(length=100), nullable=True))
    
    # Remove defaults after creation (optional, but cleaner)
    op.alter_column('meeting_dependencies', 'source_type', server_default=None)
    op.alter_column('meeting_dependencies', 'confidence_score', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_dependencies', 'created_by_agent')
    op.drop_column('meeting_dependencies', 'confidence_score')
    op.drop_column('meeting_dependencies', 'source_type')
    
    # Drop the Enum type
    dependency_source = sa.Enum('TWG_PACKET', 'AI_INFERRED', 'MANUAL', name='dependencysource')
    dependency_source.drop(op.get_bind())
    # ### end Alembic commands ###
