"""add_deal_pipeline_tables

Revision ID: 691e95d1fe77
Revises: 5585877b8180
Create Date: 2026-01-16 20:36:06.958104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691e95d1fe77'
down_revision: Union[str, Sequence[str], None] = '5585877b8180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_criteria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criterion_name', sa.String(length=100), nullable=False),
    sa.Column('criterion_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal_room_meetings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('investor_id', sa.Uuid(), nullable=False),
    sa.Column('meeting_datetime', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('meeting_status', sa.String(length=50), nullable=False),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_scores_detail',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('criterion_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('scored_by_id', sa.Uuid(), nullable=True),
    sa.Column('scored_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['scoring_criteria.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scored_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('project_id', sa.Uuid(), nullable=True))
    op.add_column('documents', sa.Column('document_type', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'documents', 'projects', ['project_id'], ['id'])
    op.add_column('investors', sa.Column('investor_type', sa.String(length=100), nullable=True))
    op.add_column('investors', sa.Column('contact_name', sa.String(length=255), nullable=True))
    op.add_column('investors', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('investors', sa.Column('total_commitments_usd', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('projects', sa.Column('funding_secured_usd', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('projects', sa.Column('is_flagship', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('projects', sa.Column('deal_room_priority', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('approved_by_id', sa.Uuid(), nullable=True))
    op.add_column('projects', sa.Column('approval_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['approved_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'approval_date')
    op.drop_column('projects', 'approved_by_id')
    op.drop_column('projects', 'deal_room_priority')
    op.drop_column('projects', 'is_flagship')
    op.drop_column('projects', 'funding_secured_usd')
    op.drop_column('investors', 'total_commitments_usd')
    op.drop_column('investors', 'contact_email')
    op.drop_column('investors', 'contact_name')
    op.drop_column('investors', 'investor_type')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'project_id')
    op.drop_table('project_scores_detail')
    op.drop_table('deal_room_meetings')
    op.drop_table('scoring_criteria')
    # ### end Alembic commands ###
