"""Add rejection status columns to Minutes

Revision ID: 72346a827bb1
Revises: 6f452664dcf1
Create Date: 2026-01-13 11:55:13.189778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72346a827bb1'
down_revision: Union[str, Sequence[str], None] = '6f452664dcf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minutes', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('minutes', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('minutes', 'rejected_at')
    op.drop_column('minutes', 'rejection_reason')
    # ### end Alembic commands ###
