"""add_external_participants

Revision ID: 8ea368f2dc2e
Revises: 495f5fdab1c6
Create Date: 2026-01-07 20:41:06.414933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea368f2dc2e'
down_revision: Union[str, Sequence[str], None] = '495f5fdab1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually ###
    # 1. Drop old PK
    op.execute("ALTER TABLE meeting_participants DROP CONSTRAINT meeting_participants_pkey")
    
    # 2. Add ID column (using gen_random_uuid())
    op.add_column('meeting_participants', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    
    # 3. Add other new columns
    op.add_column('meeting_participants', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('meeting_participants', sa.Column('email', sa.String(length=255), nullable=True))
    
    # 4. Alter user_id to nullable
    op.alter_column('meeting_participants', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
               
    # 5. Type change for rsvp_status
    # Create enum first if not exists? No, alembic handles enum creation usually if part of model.
    # Postgres ENUM handling is tricky. 'rsvpstatus' might not exist.
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'rsvpstatus') THEN CREATE TYPE rsvpstatus AS ENUM ('PENDING', 'ACCEPTED', 'DECLINED'); END IF; END $$;")

    op.alter_column('meeting_participants', 'rsvp_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='rsvpstatus'),
               existing_nullable=True,
               postgresql_using="rsvp_status::text::rsvpstatus") # Cast if needed
               
    # 6. Create new PK (id)
    op.create_primary_key("meeting_participants_pkey", "meeting_participants", ["id"])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting_participants', 'rsvp_status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='rsvpstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('meeting_participants', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('meeting_participants', 'email')
    op.drop_column('meeting_participants', 'name')
    # ### end Alembic commands ###
