"""Add reports table

Revision ID: bd2db4443c1b
Revises: 8ea368f2dc2e
Create Date: 2026-01-08 02:51:35.835562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd2db4443c1b'
down_revision: Union[str, Sequence[str], None] = '8ea368f2dc2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('twg_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('DECLARATION', 'SUMMIT_REPORT', 'POLICY_BRIEF', 'CONCEPT_NOTE', 'TECHNICAL_REPORT', 'OTHER', name='reporttype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'APPROVED', 'FINAL', name='reportstatus'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['twg_id'], ['twgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('meeting_participants', 'rsvp_status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', name='rsvpstatus'),
               nullable=False)
    op.alter_column('meeting_participants', 'attended',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting_participants', 'attended',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('meeting_participants', 'rsvp_status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', name='rsvpstatus'),
               nullable=True)
    op.drop_table('reports')
    # ### end Alembic commands ###
