"""deal_pipeline_models

Revision ID: bedc4b3e14da
Revises: 9a452664dcf3
Create Date: 2026-01-14 03:29:09.283568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bedc4b3e14da'
down_revision: Union[str, Sequence[str], None] = '9a452664dcf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector_preferences', sa.JSON(), nullable=True),
    sa.Column('ticket_size_min', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ticket_size_max', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('geographic_focus', sa.JSON(), nullable=True),
    sa.Column('investment_instruments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_investor_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('investor_id', sa.Uuid(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DETECTED', 'CONTACTED', 'INTERESTED', 'NEGOTIATING', 'COMMITTED', name='investormatchstatus'), nullable=False),
    sa.Column('meeting_scheduled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('pillar', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('lead_country', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('afcen_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('projects', sa.Column('strategic_alignment_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('projects', sa.Column('assigned_agent', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'assigned_agent')
    op.drop_column('projects', 'strategic_alignment_score')
    op.drop_column('projects', 'afcen_score')
    op.drop_column('projects', 'lead_country')
    op.drop_column('projects', 'pillar')
    op.drop_table('project_investor_matches')
    op.drop_table('investors')
    # ### end Alembic commands ###
