"""Add notifications table

Revision ID: c23b4c2df5e4
Revises: a7d59047470b
Create Date: 2025-12-27 19:02:59.976323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c23b4c2df5e4'
down_revision: Union[str, Sequence[str], None] = 'a7d59047470b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types for PostgreSQL idempotently
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notificationtype') THEN CREATE TYPE notificationtype AS ENUM ('INFO', 'SUCCESS', 'WARNING', 'ALERT', 'MESSAGE', 'DOCUMENT', 'TASK'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'minutesstatus') THEN CREATE TYPE minutesstatus AS ENUM ('DRAFT', 'REVIEW', 'APPROVED', 'FINAL'); END IF; END $$;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', postgresql.ENUM('INFO', 'SUCCESS', 'WARNING', 'ALERT', 'MESSAGE', 'DOCUMENT', 'TASK', name='notificationtype', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('documents', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint('meeting_participants_meeting_id_fkey', 'meeting_participants', type_='foreignkey')
    op.create_foreign_key(None, 'meeting_participants', 'meetings', ['meeting_id'], ['id'], ondelete='CASCADE')
    op.add_column('minutes', sa.Column('status', postgresql.ENUM('DRAFT', 'REVIEW', 'APPROVED', 'FINAL', name='minutesstatus', create_type=False), nullable=False))
    op.add_column('projects', sa.Column('investment_memo_id', sa.Uuid(), nullable=True))
    op.alter_column('projects', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_foreign_key(None, 'projects', 'documents', ['investment_memo_id'], ['id'])
    op.drop_constraint('twg_members_twg_id_fkey', 'twg_members', type_='foreignkey')
    op.create_foreign_key(None, 'twg_members', 'twgs', ['twg_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'twg_members', type_='foreignkey')
    op.create_foreign_key('twg_members_twg_id_fkey', 'twg_members', 'twgs', ['twg_id'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('projects', 'investment_memo_id')
    op.drop_column('minutes', 'status')
    op.drop_constraint(None, 'meeting_participants', type_='foreignkey')
    op.create_foreign_key('meeting_participants_meeting_id_fkey', 'meeting_participants', 'meetings', ['meeting_id'], ['id'])
    op.alter_column('documents', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_table('notifications')
    # ### end Alembic commands ###

    # Drop enum types
    postgresql.ENUM(name='notificationtype').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='minutesstatus').drop(op.get_bind(), checkfirst=True)
