"""Add video_link to meetings

Revision ID: cb9ba72d0631
Revises: ece13bd7ad72
Create Date: 2026-01-10 00:44:19.941096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9ba72d0631'
down_revision: Union[str, Sequence[str], None] = 'ece13bd7ad72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('video_link', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'video_link')
    # ### end Alembic commands ###
