"""update_rsvp_status_type

Revision ID: d6c4a5045a13
Revises: d95b84f624d1
Create Date: 2026-01-08 14:14:27.873911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c4a5045a13'
down_revision: Union[str, Sequence[str], None] = 'd95b84f624d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting_participants', 'rsvp_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='rsvpstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting_participants', 'rsvp_status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='rsvpstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
