"""restore_meeting_participant_model

Revision ID: d95b84f624d1
Revises: bd2db4443c1b
Create Date: 2026-01-08 14:11:22.603308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd95b84f624d1'
down_revision: Union[str, Sequence[str], None] = 'bd2db4443c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_column('documents', 'stage')
    op.drop_column('documents', 'ingested_at')
    op.alter_column('meeting_participants', 'rsvp_status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', name='rsvpstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting_participants', 'rsvp_status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', name='rsvpstatus'),
               existing_nullable=False)
    op.add_column('documents', sa.Column('ingested_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('stage', postgresql.ENUM('ZERO_DRAFT', 'RAP_MODE', 'DECLARATION_TXT', 'FINAL', name='documentstage'), server_default=sa.text("'FINAL'::documentstage"), autoincrement=False, nullable=False))
    op.create_table('reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('twg_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('DECLARATION', 'SUMMIT_REPORT', 'POLICY_BRIEF', 'CONCEPT_NOTE', 'TECHNICAL_REPORT', 'OTHER', name='reporttype'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'REVIEW', 'APPROVED', 'FINAL', name='reportstatus'), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='reports_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['twg_id'], ['twgs.id'], name='reports_twg_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reports_pkey')
    )
    # ### end Alembic commands ###
