"""add_vip_and_dependency_models

Revision ID: e637b1a43493
Revises: 22e40a99295e
Create Date: 2026-01-11 13:37:55.206151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e637b1a43493'
down_revision: Union[str, Sequence[str], None] = '22e40a99295e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vip_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=False),
    sa.Column('companies', sa.String(length=255), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('calendar_sync_token', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_twg_id', sa.Uuid(), nullable=False),
    sa.Column('target_twg_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SATISFIED', 'BLOCKED', name='dependencystatus'), nullable=False),
    sa.Column('blocking_meeting_id', sa.Uuid(), nullable=True),
    sa.Column('blocking_document_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blocking_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['blocking_meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['source_twg_id'], ['twgs.id'], ),
    sa.ForeignKeyConstraint(['target_twg_id'], ['twgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependencies')
    op.drop_table('vip_profiles')
    # ### end Alembic commands ###
