"""add weekly packet table

Revision ID: f2ca45523328
Revises: 0e1b80868408
Create Date: 2026-01-11 00:23:29.115670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ca45523328'
down_revision: Union[str, Sequence[str], None] = '0e1b80868408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_packets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('twg_id', sa.Uuid(), nullable=False),
    sa.Column('week_start_date', sa.DateTime(), nullable=False),
    sa.Column('proposed_sessions', sa.JSON(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('accomplishments', sa.JSON(), nullable=False),
    sa.Column('risks_and_blockers', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['twg_id'], ['twgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_packets')
    # ### end Alembic commands ###
