"""Add metadata_json to conflicts

Revision ID: fe5cd4954a45
Revises: bedc4b3e14da
Create Date: 2026-01-14 13:10:52.041340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5cd4954a45'
down_revision: Union[str, Sequence[str], None] = 'bedc4b3e14da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conflicts', sa.Column('metadata_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conflicts', 'metadata_json')
    # ### end Alembic commands ###
