"""
Enhanced chat message schemas for rich UI communication.

This module defines message types, actions, and schemas for the enhanced
agent chat interface with support for proactive suggestions, commands,
agent requests, and tool execution visibility.

Note: This is different from agent_messages.py which handles agent-to-agent
communication. This file handles user-to-agent chat UI messages.
"""

from enum import Enum
from typing import Optional, List, Dict, Any
from datetime import datetime
from uuid import UUID, uuid4
from pydantic import BaseModel, Field


class ChatMessageType(str, Enum):
    """Types of messages in the chat UI."""
    USER_TEXT = "user_text"
    AGENT_TEXT = "agent_text"
    AGENT_SUGGESTION = "agent_suggestion"
    AGENT_REQUEST = "agent_request"  # Agent asking for input
    SYSTEM = "system"
    TOOL_EXECUTION = "tool_execution"
    FILE_ATTACHMENT = "file_attachment"
    COMMAND_RESULT = "command_result"


class ActionType(str, Enum):
    """Types of interactive actions in messages."""
    BUTTON = "button"
    FILE_UPLOAD = "file_upload"
    FORM_INPUT = "form_input"
    DROPDOWN = "dropdown"
    CONFIRM = "confirm"


class MessageAction(BaseModel):
    """Interactive action that can be attached to a message."""
    action_id: str = Field(default_factory=lambda: str(uuid4()))
    action_type: ActionType
    label: str
    value: Optional[Any] = None
    style: str = "primary"  # primary, secondary, success, danger
    icon: Optional[str] = None  # Material Symbol icon name
    handler_endpoint: Optional[str] = None  # Backend endpoint to call


class FileAttachment(BaseModel):
    """File attachment in a message."""
    file_id: str
    filename: str
    file_type: str
    file_size: int  # bytes
    url: Optional[str] = None
    thumbnail_url: Optional[str] = None


class ChatMessage(BaseModel):
    """Enhanced message for chat UI with rich content support."""
    message_id: UUID = Field(default_factory=uuid4)
    conversation_id: UUID
    message_type: ChatMessageType
    content: str
    sender: str  # "user", "agent", "system"
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    # Rich content
    metadata: Optional[Dict[str, Any]] = None
    actions: List[MessageAction] = Field(default_factory=list)
    attachments: List[FileAttachment] = Field(default_factory=list)

    # Suggestion-specific fields
    suggestion_type: Optional[str] = None
    suggestion_data: Optional[Dict[str, Any]] = None

    # Request-specific fields (when agent asks for input)
    request_type: Optional[str] = None  # "file_upload", "confirmation", "selection", "input"
    request_schema: Optional[Dict[str, Any]] = None

    # Tool execution visibility
    tool_name: Optional[str] = None
    tool_status: Optional[str] = None  # "running", "success", "error"
    tool_result: Optional[Dict[str, Any]] = None

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat(),
            UUID: lambda v: str(v)
        }


class AgentSuggestion(BaseModel):
    """Proactive suggestion generated by the agent."""
    suggestion_id: UUID = Field(default_factory=uuid4)
    title: str
    description: str
    suggestion_type: str  # "draft_document", "schedule_meeting", "send_email", etc.
    priority: str = "medium"  # "high", "medium", "low"
    action_data: Dict[str, Any]  # Data needed to execute the suggestion
    icon: Optional[str] = None  # Material Symbol icon name
    expires_at: Optional[datetime] = None  # When suggestion should auto-dismiss
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat(),
            UUID: lambda v: str(v)
        }


class ToolExecution(BaseModel):
    """Record of a tool execution during agent processing."""
    execution_id: UUID = Field(default_factory=uuid4)
    tool_name: str
    status: str  # "running", "success", "error"
    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat(),
            UUID: lambda v: str(v)
        }


# Request/Response Schemas

class EnhancedChatRequest(BaseModel):
    """Enhanced chat request with optional attachments."""
    message: str
    conversation_id: Optional[UUID] = None
    twg_id: Optional[str] = None
    attachments: List[Dict[str, Any]] = Field(default_factory=list)


class EnhancedChatResponse(BaseModel):
    """Enhanced chat response with rich content."""
    message: ChatMessage
    suggestions: List[AgentSuggestion] = Field(default_factory=list)
    tool_executions: List[ToolExecution] = Field(default_factory=list)
    conversation_id: UUID

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat(),
            UUID: lambda v: str(v)
        }


class SuggestionAcceptRequest(BaseModel):
    """Request to accept and execute a suggestion."""
    suggestion_id: UUID


class AgentRequestResponse(BaseModel):
    """User's response to an agent request."""
    request_id: UUID
    response_data: Dict[str, Any]
